export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_FAILURE = 'GET_PROJECT_LIST_FAILURE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const POST_NEW_PROJECT_FAILURE = 'POST_NEW_PROJECT_FAILURE';

export const GET_PROJECT_DETAIL_PENDING = 'GET_PROJECT_DETAIL_PENDING';
export const GET_PROJECT_DETAIL_SUCCESS = 'GET_PROJECT_DETAIL_SUCCESS';
export const GET_PROJECT_DETAIL_FAILURE = 'GET_PROJECT_DETAIL_FAILURE';
